import account from "./account";
import agent from "./agent";
import job from "./job";
import text from "./text";
import image from "./image";
export const accountsRouter = account;
export const agentsRouter = agent;
export const jobsRouter = job;
export const textsRouter = text;
export const imagesRouter = image;
